### ISSUE TITLE
No Blocks appear in playground

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#126]
No Blocks appear in playgound. 
microbit and other works, bot not Calliope mini.

![grafik](https://user-images.githubusercontent.com/37311672/95493387-b455c480-099c-11eb-9255-2a50d3a4d891.png)

**Comment by joernalraun** [comment]
When I check the default one (hello) it does work for me. Have you tried different code?

**Comment by Amerlander** [comment]
It also works for me.
Except the WordPicker seems a bit strange, since it picks letters not words and even this doesn't work - but that's also happening in the other editors.

Do you get any errors in the browsers console? (CTRL+Shift+I und dann den Reiter "Konsole" wählen)
I get some in Firefox, but it still works. No errors are appearing in Chrome.

![image](https://user-images.githubusercontent.com/3764089/95519705-f5ae9a00-09c5-11eb-8906-ddebb31a4515.png)


![image](https://user-images.githubusercontent.com/3764089/95519443-5d181a00-09c5-11eb-9b9d-34975d5ea8d9.png)

**Comment by MKleinSB** [comment]
Tested it today again, now it works!
Perhaps only a problem with cache...
Sorry!
