### ISSUE TITLE
generated .hex files don´t run on Calliope V1.3

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#170]
Generated hexfiles only run on Calliope V2 but not on Calliope V1.3 (V1.2 not tested)
![grafik](https://user-images.githubusercontent.com/37311672/160234120-fa4ee167-5b10-4bae-ae66-ae7e2b56ff18.png)

**Comment by joernalraun** [comment]
This is because of the fact that we will be able to make use of the 32KB of the Rev2.0 processor. This files are not compatible! You can change this within the settings of your current project. However, the switch has no effect currently (read more about this at #161).

**Comment by MKleinSB** [comment]
I think this way is not easy enough for Children to find. No way to autodetect the version of the mini?

**Comment by Amerlander** [comment]
For the final version, we will try to get a better solution – maybe a dialog when you open a new project to choose your device. But first we have to be able to switch the settings at all. Also, the 16KB device has some other problems in the new version and is more likely to crash, so that will also be something we have to solve.

**Comment by Amerlander** [comment]
If we get it stable on the 16KB devices, we could also make 16KB the default (which works on both devices) and have the 32KB as an option.

**Comment by MKleinSB** [comment]
That would be the most practicable solution I think. For most schoolprojects 16k would be enough if not, you can switch to 32kb.
